In [4]:
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

###  In order to demonstrate the cosine similarity function, we need vectors. Here vectors are NumPy array. Let’s create NumPy array.

In [24]:
array_vec_1 = np.array([[12,41,60,11,21]])
array_vec_3 = np.array([[12,41,60,11,21]])
array_vec_2 = np.array([[40,11,4,11,14]]) 
array_vec_4 = np.array([[5,5,5,5,5]])

### Finally, Once we have vectors, We can call cosine_similarity() by passing both vectors. It will calculate the cosine similarity between these two. It will be a value between [0,1]. If it is 0 then both vectors are completely different. But in the place of that, if it is 1, It will be completely similar.

In [25]:
cosine_similarity(array_vec_1 , array_vec_2)

array([[0.45227058]])

In [26]:
cosine_similarity(array_vec_1 , array_vec_3)

array([[1.]])

In [27]:
cosine_similarity(array_vec_2 , array_vec_4)

array([[0.78941389]])