In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn import svm
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [3]:
data= pd.read_csv("diabetes1.csv")

In [4]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [6]:
X=data.iloc[:,:8]
X.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  
0                     0.627   50  
1                     0.351   31  
2                     0.672   32  
3                     0.167   21  
4                     2.288   33

In [7]:
y = data["Outcome"]
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)
model = svm.SVC(C=2, gamma='scale', kernel='linear')
model.fit(X_train, y_train)
prediction = model.predict(X_test)

In [9]:
print(confusion_matrix(y_test, prediction))

[[90 13]
 [20 31]]


In [10]:
print(classification_report(y_test, prediction))

              precision    recall  f1-score   support

           0       0.82      0.87      0.85       103
           1       0.70      0.61      0.65        51

    accuracy                           0.79       154
   macro avg       0.76      0.74      0.75       154
weighted avg       0.78      0.79      0.78       154



In [13]:
print(X_train.shape)

(614, 8)


In [14]:
X_train

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
709            2       93             64             32      160  38.0   
425            4      184             78             39      277  37.0   
135            2      125             60             20      140  33.8   
630            7      114             64              0        0  27.4   
500            2      117             90             19       71  25.2   
..           ...      ...            ...            ...      ...   ...   
75             1        0             48             20        0  24.7   
599            1      109             38             18      120  23.1   
575            1      119             44             47       63  35.5   
337            5      115             76              0        0  31.2   
523            9      130             70              0        0  34.2   

     DiabetesPedigreeFunction  Age  
709                     0.674   23  
425                     0.264   31  
135                     0.088   31  
630                     0.732   34  
500                     0.313   21  
..                        ...  ...  
75                      0.140   22  
599                     0.407   26  
575                     0.280   25  
337                     0.343   44  
523                     0.652   45  

[614 rows x 8 columns]

In [15]:
y_train

709    1
425    1
135    0
630    1
500    0
      ..
75     0
599    0
575    0
337    1
523    1
Name: Outcome, Length: 614, dtype: int64

In [16]:
X_test

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
766            1      126             60              0        0  30.1   
748            3      187             70             22      200  36.4   
42             7      106             92             18        0  22.7   
485            0      135             68             42      250  42.3   
543            4       84             90             23       56  39.5   
..           ...      ...            ...            ...      ...   ...   
603            7      150             78             29      126  35.2   
510           12       84             72             31        0  29.7   
171            6      134             70             23      130  35.4   
672           10       68            106             23       49  35.5   
298           14      100             78             25      184  36.6   

     DiabetesPedigreeFunction  Age  
766                     0.349   47  
748                     0.408   36  
42                      0.235   48  
485                     0.365   24  
543                     0.159   25  
..                        ...  ...  
603                     0.692   54  
510                     0.297   46  
171                     0.542   29  
672                     0.285   47  
298                     0.412   46  

[154 rows x 8 columns]

In [16]:
y_test

766    1
748    1
42     0
485    1
543    0
      ..
603    1
510    1
171    1
672    0
298    1
Name: Outcome, Length: 154, dtype: int64

In [11]:
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)

In [12]:
X_train[:5, :]

array([[-0.5288778 , -0.8564829 , -0.26068567,  0.71310347,  0.67162457,
         0.73836846,  0.62083528, -0.86196915],
       [ 0.07415093,  1.97417637,  0.46240372,  1.15044918,  1.67011727,
         0.61132398, -0.64915711, -0.19012014],
       [-0.5288778 ,  0.13891377, -0.46728263, -0.03663203,  0.50094206,
         0.20478164, -1.19432458, -0.19012014],
       [ 0.97869401, -0.20325384, -0.26068567, -1.2861912 , -0.69383553,
        -0.60830305,  0.80049274,  0.06182324],
       [-0.5288778 , -0.1099354 ,  1.08219462, -0.09910999, -0.08791261,
        -0.88780091, -0.49737753, -1.0299314 ]])

In [13]:
for k in ('linear', 'poly', 'rbf', 'sigmoid'):
    model = svm.SVC(kernel=k)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_train)
    print(k)
    print(accuracy_score(y_train, y_pred))

linear
0.7785016286644951
poly
0.7980456026058632
rbf
0.8208469055374593
sigmoid
0.6693811074918566


In [14]:
model = svm.SVC(kernel='rbf')
model.fit(X_train, y_train)

SVC()

In [15]:
patient = np.array([[ 1, 150, 70, 45, 0, 40.6, 1.5, 25]])
patient = scaler.transform(patient)
model.predict(patient)

C:\Users\kshyk\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [16]:
patient = np.array([[1, 50, 70, 45, 0, 40.0, 1.5, 25]])
patient = scaler.transform(patient)
model.predict(patient)

C:\Users\kshyk\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([0], dtype=int64)

In [27]:
a=int(input("Please enter Number of times pregnant(Pregnancies)? : "))
b=int(input("Please enter the value of  Plasma glucose concentration a 2 hours in an oral glucose tolerance test(Gulcose)? :"))
c=int(input("Please enter the value of Diastolic blood pressure in mm Hg (Blood Pressure)? : "))
d=int(input("Please enter the value of Triceps skin fold thickness in mm (Skin Thickness)? : "))
e=int(input("Please enter the value of 2-Hour serum insulin in mu U/ml (Insulin)? : "))
f=float(input("Please enter the value of Body mass index (weight in kg/(height in m)^2) (BMI)? : "))
g=float(input("Please enter the value of Diabetes pedigree function? (Diabetes Pedigree Function): "))
h=int(input("Please enter the value of age? (Age)"))

Please enter Number of times pregnant(Pregnancies)? : 1
Please enter the value of  Plasma glucose concentration a 2 hours in an oral glucose tolerance test(Gulcose)? :150
Please enter the value of Diastolic blood pressure in mm Hg (Blood Pressure)? : 70
Please enter the value of Triceps skin fold thickness in mm (Skin Thickness)? : 45
Please enter the value of 2-Hour serum insulin in mu U/ml (Insulin)? : 0
Please enter the value of Body mass index (weight in kg/(height in m)^2) (BMI)? : 40.6
Please enter the value of Diabetes pedigree function? (Diabetes Pedigree Function): 1.5
Please enter the value of age? (Age)25


In [ ]:
patient = np.array([[ a,b,c,d,e,f,g,h]])
patient = scaler.transform(patient)
model.predict(patient)

In [29]:
result = model.predict(patient)
if result == 1:
    print("Positive")
else:
    print('Negative')

Positive
