In [1]:
conda install numpy


Solving environment: ...working... done

## Package Plan ##

  environment location: C:\Users\kshyk\anaconda3

  added / updated specs:
    - numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-22.9.0               |   py39haa95532_0         888 KB
    ------------------------------------------------------------
                                           Total:         888 KB

The following packages will be UPDATED:

  conda                               4.12.0-py39haa95532_0 --> 22.9.0-py39haa95532_0




conda-22.9.0         | 888 KB    |            |   0% 
conda-22.9.0         | 888 KB    | 1          |   2% 
conda-22.9.0         | 888 KB    | #4         |  14% 
conda-22.9.0         | 888 KB    | ##3        |  23% 
conda-22.9.0         | 888 KB    | ###        |  31% 
conda-22.9.0         | 888 KB    | #####2     |  52% 
conda-22.9.0         | 888 KB    | ########4  |  85% 
c

In [2]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
for i in range(0,6):
    print(a[i])

1
2
3
4
5
6


In [3]:
ls=[1,2,3,5,4,7]
d=np.array(ls)
print(type(d))
print(d)

<class 'numpy.ndarray'>
[1 2 3 5 4 7]


In [4]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# for i in range(0,3):
#     for j in range(0,4):
#         print(a[i][j])
        
d=a.ndim
print(d)

e=a.size
print(e)

f=a.shape
print(f)

2
12
(3, 4)


In [6]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.zeros(3)

array([0., 0., 0.])

In [23]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [24]:
# Return evenly spaced values within a given interval
# arange can be called with a varying number of positional arguments
# arange(stop): Values are generated within the half-open interval [0, stop).
# arange(start, stop): Values are generated within the half-open interval [start, stop)
# arange(start, stop, step) Values are generated within the half-open interval [start, stop),
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [9]:
# reshape--> is used to change the dimension of the array
a = np.arange(40)
print(a)
b=a.reshape(2,5,2,2)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]

  [[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]

  [[16 17]
   [18 19]]]


 [[[20 21]
   [22 23]]

  [[24 25]
   [26 27]]

  [[28 29]
   [30 31]]

  [[32 33]
   [34 35]]

  [[36 37]
   [38 39]]]]


In [27]:
# Eye Function---> used to create an identity matrix
# the eye() function is used to create a 2-D array with ones on the diagonal and zeros elsewhere.
# N--> number of rows
d=np.eye(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# 1. random number generation
# Random number does NOT mean a different number every time. Random means something that can not be predicted logically
# NumPy offers the random module to work with random numbers


from numpy import random
# x = random.randint(100)  # give any random number between 0,100
# print(x)

# 2.The random module's rand() method returns a random float between 0 and 1
from numpy import random
x = random.rand()
print(x)

In [13]:
np.random.randint(0,100,10) # 0 and 100 ke vich me se 10 value return karega
np.random.randint(0,100)

52

In [ ]:
from numpy import random
d=random.randint(0,2)
e=int(input("Enter your number:"))
if(e==d):
    print("You won the game")
else:
    print("you lose the game")

In [51]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b=a.shape
print(b)
c=len(b)

(3, 4)
2


In [1]:
# Generate a 2-D array with 3 rows, each row containing 5 random numbers
from numpy import random
x = random.rand(3, 5)
print(x)

[[0.81092467 0.40978808 0.46243568 0.83850655 0.627316  ]
 [0.2592705  0.89126034 0.03827999 0.07459774 0.65479994]
 [0.99778688 0.60823917 0.08403258 0.76164592 0.83375195]]


In [62]:
# The choice() method also allows you to return an array of values
from numpy import random
x = random.choice([3, 5, 7, 9])
print(x)

7


In [64]:
print(a.dtype)

int32


In [72]:
# The empty() function is used to create a new array of given shape and type, without initializing entries
d=np.empty([3,4], dtype=int)
print(d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [67]:
# numpy.full(shape, fill_value, dtype = None, order = ‘C’) : Return a new array with the same shape and type as 
# a given array filled with a fill_value
d=np.full([3,3],55)
print(d)

[[55 55 55]
 [55 55 55]
 [55 55 55]]


In [70]:
# create an array filled with all ones
d=np.ones([3,4])
print(d)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [75]:
# print the most occured element in an array
x=np.array([1,2,3,3,3,1,1,1,4,4,4,4,4,4,4,5,5,1,3])
y=np.bincount(x).argmax()
print(y)

4


In [89]:
x=np.array([1,2,3,3,3,1,1,1,4,4,4,4,4,4,4,5,5,1,3,98])
y=np.bincount(x)
print(y)

[0 5 1 4 7 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]


In [83]:
g=np.array([1,2,3,4,5,6])
g.shape=(3,2)
g


array([[1, 2],
       [3, 4],
       [5, 6]])

In [86]:
arr=np.arange(0,11)
arr[1:5]

array([1, 2, 3, 4])

In [88]:
arr[0:5]=100
print(arr)

[100 100 100 100 100   5   6   7   8   9  10]


In [91]:
arr=np.arange(0,11)
print(arr)
slice_of_arr=arr[4:8]
slice_of_arr

[ 0  1  2  3  4  5  6  7  8  9 10]


array([4, 5, 6, 7])

In [92]:
slice_of_arr[:]=99
arr

array([ 0,  1,  2,  3, 99, 99, 99, 99,  8,  9, 10])

In [95]:
# indexing of 2D array
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [106]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.array([[3, 2, 5, 4], [5, 6, 6, 8], [9, 10, 34, 12]])
d=np.add(a,b)
print(d)

[[ 4  4  8  8]
 [10 12 13 16]
 [18 20 45 24]]


In [100]:
np.sum(a, axis=0)
np.sum(a)

78

In [107]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a+2)
print(a-4)
print(a*3)
print(a/2)
print(a**2)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[[-3 -2 -1  0]
 [ 1  2  3  4]
 [ 5  6  7  8]]
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]]
[[0.5 1.  1.5 2. ]
 [2.5 3.  3.5 4. ]
 [4.5 5.  5.5 6. ]]
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]


In [113]:
print(np.min(a))
print(np.max(a))

1
12


In [ ]:
# matmul() function returns the matrix product of two arrays


In [114]:
#  create a array of 10 zeroes
d=np.zeros(10)
print(d)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [115]:
# create an array of 10 ones
d=np.ones(10)
print(d)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [122]:
d=np.full(10,5)
print(d)

[5 5 5 5 5 5 5 5 5 5]


In [120]:
d=np.arange(10,51)
print(d)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [124]:
d=np.arange(0,9)
print(d)
print(d.reshape(3,3))

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [138]:
y=random.rand()
print(y)

0.6086277166332257


In [137]:
# increment value cannot be float
np.linspace(0,25,10)

array([ 0.        ,  2.77777778,  5.55555556,  8.33333333, 11.11111111,
       13.88888889, 16.66666667, 19.44444444, 22.22222222, 25.        ])

In [141]:
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [147]:
print(mat[2,1:])

[12 13 14 15]


In [146]:
print(mat[3:,0:])

[[16 17 18 19 20]
 [21 22 23 24 25]]


In [148]:
print(np.std(mat))

7.211102550927978


In [150]:
print(mat.sum(axis=0))

[55 60 65 70 75]


In [152]:
print(mat.sum(axis=1))

[ 15  40  65  90 115]


In [168]:
a=np.array([1,2,3,2,3,4,0,3,4,5,6])
# print(a.ndim)
b=np.array([7,2,10,0,2,7,4,0,9,2,2,8])
np.intersect1d(a,b)

array([0, 2, 4])

In [16]:
import numpy as np 
a=np.array([1,2,3,2,3,4,0,3,4,5,6])
b=np.array([7,2,10,0,2,7,4,0,9,2,8])
c=len(a)
d=len(b)
for i in range(0,c):
    if a[i] in b:
        print(np.delete(b,a[i]))


[7 2 0 2 7 4 0 9 2 8]
[7 2 0 2 7 4 0 9 2 8]
[ 7  2 10  0  7  4  0  9  2  8]
[ 2 10  0  2  7  4  0  9  2  8]
[ 7  2 10  0  7  4  0  9  2  8]


In [ ]:
# Series is a powerful version of Excel
