In [1]:
import cv2 
import os

In [2]:
#cascade classifier
cascPath=os.path.dirname(cv2.__file__)+"/data/haarcascade_frontalface_default.xml"
face=cv2.CascadeClassifier(cascPath)
img=cv2.imread("H.jpg")
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
faces=face.detectMultiScale(gray)
print(type(faces))

<class 'numpy.ndarray'>


In [ ]:
if len(faces)==0:
    print("no faces found!")
else:
    print(faces)
    print(faces.shape)
    print("no. of faces detected:"+str(faces.shape[0]))
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),1)
cv2.putText(img,"no. of faces detected:"+str(faces.shape[0]),(0,img.shape[0]-10),cv2.FONT_HERSHEY_TRIPLEX,1,(255,0,0))
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[334  48  80  80]
 [101 153  58  58]
 [163  48  62  62]
 [186 175  76  76]
 [240 233  62  62]
 [289 220  69  69]
 [365 202  72  72]
 [266 107  64  64]]
(8, 4)
no. of faces detected:8
