# Naive Bayes Algorithm : Supervised Algorithm

### Used in NLP Most,spam filtering

In [1]:
from sklearn import preprocessing


In [2]:
from sklearn.naive_bayes import GaussianNB

In [3]:
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny','Rainy','Sunny','Overcast','Overcast','Rainy']

In [4]:
temp=['High','High','High','Medium','Low','Low','Low','Medium','Low','Medium','Medium','Medium','High','Medium']

In [5]:
play=['No','No','Yes','Yes','Yes','No','Yes','Yes','No','Yes','Yes','Yes','Yes','No']

In [6]:
le=preprocessing.LabelEncoder()

In [7]:
weather_encoded=le.fit_transform(weather)

In [8]:
temp_encoded=le.fit_transform(temp)


In [9]:
label=le.fit_transform(play)

In [10]:
print(weather_encoded,temp_encoded,label)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1] [0 0 0 2 1 1 1 2 1 2 2 2 0 2] [0 0 1 1 1 0 1 1 0 1 1 1 1 0]


In [11]:
features=list(zip(weather_encoded,temp_encoded))

In [12]:
model=GaussianNB()
model.fit(features,label)

GaussianNB()

In [13]:
print('Enter Weather and Humidity Conditions: ')
w,h=map(int,input().split())
predicted=model.predict(([[w,h]]))
predicted

Enter Weather and Humidity Conditions: 
2 0


array([0], dtype=int64)

In [46]:
from sklearn.datasets import load_iris
import pandas as pd

# Load Data
iris = load_iris()
# iris.feature_names
# iris.target
# Create a dataframe
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df['target'] = iris.target
X = iris.data
df


sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [15]:
df.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)      target  
count        150.000000  150.000000  
mean           1.199333    1.000000  
std            0.762238    0.819232  
min            0.100000    0.000000  
25%            0.300000    0.000000  
50%            1.300000    1.000000  
75%            1.800000    2.000000  
max            2.500000    2.000000

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 5.4 KB


In [17]:
target=df.target

In [40]:
X=df[['sepal length (cm)','sepal width (cm)','petal length (cm)','petal width (cm)']]
y=df['target']

In [19]:
from sklearn.model_selection import train_test_split
gb=GaussianNB()
gb.fit(X,y)

GaussianNB()

In [20]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)

In [21]:
gb.fit(X_train,y_train)

GaussianNB()

In [22]:
# import numpy as np
# a=float(input('sepal length: '))
# b=float(input('sepal width: '))
# c=float(input('petal length: '))
# d=float(input('petal width: '))
# e=np.array([[a,b,c,d]])

In [23]:
pred=gb.predict(X_test)
pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 2, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

In [24]:
pred

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 2, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0, 1, 1, 2, 1, 2])

In [25]:
for i in pred:
    if i==0:
        print("Setosa")
    elif i==1:
        print('Versicolor')
    else:
        print('Verginica')

Versicolor
Setosa
Verginica
Versicolor
Versicolor
Setosa
Versicolor
Verginica
Versicolor
Versicolor
Verginica
Setosa
Setosa
Setosa
Setosa
Verginica
Verginica
Versicolor
Versicolor
Verginica
Setosa
Verginica
Setosa
Verginica
Verginica
Verginica
Verginica
Verginica
Setosa
Setosa
Setosa
Setosa
Versicolor
Setosa
Setosa
Verginica
Versicolor
Setosa
Setosa
Setosa
Verginica
Versicolor
Versicolor
Setosa
Setosa
Versicolor
Versicolor
Verginica
Versicolor
Verginica


In [32]:
from sklearn import metrics
from sklearn.metrics import classification_report,confusion_matrix

In [27]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      0.93      0.93        15
           2       0.94      0.94      0.94        16

    accuracy                           0.96        50
   macro avg       0.96      0.96      0.96        50
weighted avg       0.96      0.96      0.96        50



In [33]:
print(confusion_matrix(y_test,pred))

[[19  0  0]
 [ 0 14  1]
 [ 0  1 15]]


In [48]:
print(metrics.accuracy_score(y_test,pred))
print('The accuracy of model is',metrics.accuracy_score(y_test,pred)*100,'%')

0.96
The accuracy of model is 96.0 %
